### ISSUE TITLE
Crashes using subdomain

### ISSUE THREAD

**Issue by MarkMurphy** [proxylocal/proxylocal-gem#15]
After attempting to access the the proxylocal url, it will crash.

``` shell
proxylocal "http://api.localhost.com:3000"
Local server on port http://api.localhost.com:3000 is now publicly available via:
http://plik.t.proxylocal.com/
Connection has been terminated
/Users/mark/.rvm/gems/ruby-2.1.2@global/gems/eventmachine-1.0.3/lib/eventmachine.rb:1516:in `klass_from_handler': "http://api.localhost.com:3000" is not a class/module (TypeError)
    from /Users/mark/.rvm/gems/ruby-2.1.2@global/gems/eventmachine-1.0.3/lib/eventmachine.rb:658:in `bind_connect'
    from /Users/mark/.rvm/gems/ruby-2.1.2@global/gems/eventmachine-1.0.3/lib/eventmachine.rb:640:in `connect'
    from /Users/mark/.rvm/gems/ruby-2.1.2@global/gems/proxylocal-0.3.1/lib/proxylocal/client.rb:88:in `receive_connection'
    from /Users/mark/.rvm/gems/ruby-2.1.2@global/gems/proxylocal-0.3.1/lib/proxylocal/protocol.rb:20:in `receive_object'
    from /Users/mark/.rvm/gems/ruby-2.1.2@global/gems/eventmachine-1.0.3/lib/em/protocols/object_protocol.rb:27:in `receive_data'
    from /Users/mark/.rvm/gems/ruby-2.1.2@global/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    from /Users/mark/.rvm/gems/ruby-2.1.2@global/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    from /Users/mark/.rvm/gems/ruby-2.1.2@global/gems/proxylocal-0.3.1/lib/proxylocal/client.rb:24:in `run'
    from /Users/mark/.rvm/gems/ruby-2.1.2@global/gems/proxylocal-0.3.1/lib/proxylocal/command.rb:74:in `<top (required)>'
    from /Users/mark/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/mark/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/mark/.rvm/gems/ruby-2.1.2@global/gems/proxylocal-0.3.1/bin/proxylocal:4:in `<top (required)>'
    from /Users/mark/.rvm/rubies/ruby-2.1.2/bin/proxylocal:23:in `load'
    from /Users/mark/.rvm/rubies/ruby-2.1.2/bin/proxylocal:23:in `<main>'
    from /Users/mark/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
    from /Users/mark/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by lest** [comment]
Unfortunately you cannot pass URL as argument as `proxylocal` command expects the argument to be a port number.
